name: ci
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: ./client
        run: npm i
      - name: Run linter
        working-directory: ./client
        run: npm run lint
      - name: Run tests
        working-directory: ./client
        run: npm run test
