name: Load Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up k6
        run: |
          sudo apt update
          sudo apt install -y k6

      - name: Run k6 load test
        run: |
          mkdir -p results
          k6 run ./performance-test/performace.test.js | tee results/k6-load-test.log

      - name: Commit load test results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add results/k6-load-test.log
          git commit -m "Add load test results"
          git push
